### ISSUE TITLE
请求头获取不到Content-Length

### ISSUE THREAD

**Issue by zzh3321** [huangtaoOO/TaoComponent#2]
大佬你好。使用发现两个问题：

1、请求头获取不到Content-Length，可能是后端没有按照标准协议返回数据。经测试在obtainTotalSize方法中，执行一次connection.connect()，即可获取到。

2、快速点击demo中的下载按钮，progress会多次叠加。并且偶发了一次空指针，没有抓到。(꒦_꒦)

想问下大佬这个库会长期维护吗，看有没有机会在正式项目中使用 哈哈

**Comment by huangtaoOO** [comment]
问题1是否有对应的链接提供测试呢？问题2已了解，会近期提供修复

**Comment by zzh3321** [comment]
链接不方便公开，可以加下QQ吗，331695147

**Comment by huangtaoOO** [comment]
QQ:1462320178

**Comment by huangtaoOO** [comment]
修复版本：0.0.7
